version: '3.8'

services:
  zanshin-app:
    build: .
    container_name: zanshin_dojo_dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules # Evita sobrescrever os módulos do container
    environment:
      - CHOKIDAR_USEPOLLING=true # Necessário para o Hot Reload no Linux
    stdin_open: true
    tty: true
